----------------------------------------------------------------------------------
-- Includes
----------------------------------------------------------------------------------

include "../../GXLua/Premake.lua"

----------------------------------------------------------------------------------
-- Project
----------------------------------------------------------------------------------

project "GXQt"
	GX.Premake.project("GXQt", {GX.Premake.Kind.DLL, GX.Premake.Kind.Static})
	GX.Premake.import_gx("../../", {"GXGfx", "GXLib"})
	GX.Premake.import_qt("../../../../Libraries/Qt/5.13.1/msvc2017_64", {"core", "gui", "widgets"})
	GX.Premake.enable_pch("../Source/Core/PCH.cpp", "GXQt/Core/PCH.h");
	
	disablewarnings {
		"4127", -- conditional expression is constant
		"4458", -- declaration of 'X' hides class member
	}
	
	linkoptions {
		-- Generated by statically linking Qt.
		"-IGNORE:4006", -- "X already defined in Y.obj; second definition ignored"
	}	